### ISSUE TITLE
runtime error in preprocess.py: does not have a __getstate__ method defined

### ISSUE THREAD

**Issue by accocca** [yistLin/dvector#9]
I run the code in preprocess.py and it has an error:
`Traceback (most recent call last):
  File "preprocess.py", line 92, in <module>
    preprocess(**vars(PARSER.parse_args()))
  File "preprocess.py", line 71, in preprocess
    for speaker_name, mel_tensor in tqdm(dataloader, ncols=0, desc="Preprocess"):
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 359, in __iter__
    return self._get_iterator()
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 305, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 918, in __init__
    w.start()
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Users/xinyuewang/opt/anaconda3/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
RuntimeError: Tried to serialize object __torch__.data.wav2mel.Wav2Mel which does not have a __getstate__ method defined!
`
does anyone know how to solve this?
my version:
`python==3.8
torch==1.8.0
torchaudio==0.8.0`

**Comment by accocca** [comment]
already solved.
just change in preprocess.py:
`dataloader = DataLoader(dataset, batch_size=1, num_workers=cpu_count())`
to
`dataloader = DataLoader(dataset, batch_size=1, num_workers=0)`
the problem will be solved!
